### ISSUE TITLE
Unable to create vm

### ISSUE THREAD

**Issue by timon-schelling** [ivan-hc/Boxes-appimage#1]
I'm unable to create any vm, seems to be issue https://bugs.launchpad.net/ubuntu/+source/gnome-boxes/+bug/2019254

Logs:
```
Gtk-Message: 13:59:33.283: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:59:33.294: Failed to load module "canberra-gtk-module"

(gnome-boxes:18354): Boxes-WARNING **: 13:59:58.806: util-app.vala:442: Failed to execute: virsh capabilities
rm: cannot remove '[': Read-only file system
```

maybe https://bugs.launchpad.net/ubuntu/+source/gnome-boxes/+bug/2019254/comments/3 helps to fix the issue, I think just a missing dependency.

**Comment by ivan-hc** [comment]
Hi, just included "[libvirt](https://archlinux.org/packages/extra/x86_64/libvirt/)", after GH actions have finished we should find a solution to execute "libvirtd" in JuNest in proot mode.

**Comment by ivan-hc** [comment]
UPDATE: nothing happens, GNOME Boxes still crashes when I try to download/install a distro from the list.

**Comment by timon-schelling** [comment]
I will try to Boot from iso. Thanks for trying.

**Comment by timon-schelling** [comment]
Booting from Iso still leads to the described error. I thought might be an easy fix. :( Do you have other ideas?

**Comment by ivan-hc** [comment]
I don't really know, I've tried to run GNOME Boxes in first from JuNest, then by mounting all the other paths (/var, /dev/, /tmp...) without success. I still waiting an answer from this issue https://github.com/fsquillace/junest/issues/337

**Comment by ivan-hc** [comment]
hi, ofter one year I'm finally here to announce that I've changed method to create this kind of AppImages.

Just yesterday I created VirtualBox AppImage https://github.com/ivan-hc/VirtualBox-appimage

Now I'll try to made this project work, you can already download and test the release

https://github.com/ivan-hc/Boxes-appimage/releases/tag/continuous

in case you need Nvidia drivers for it, the AppImage will download them for you, using Conty https://github.com/Kron4ek/Conty

This is the new base I use for AppImages requiring hardware accelleration, a bit bigger but its the one that works the most.

Feel free to open another issue in case of problems with the new releases.  I close this.
