### ISSUE TITLE
virtualbox and boxes are share conty folder , cannot run

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/Boxes-appimage#4]
when i run virtualbox is auto create 
![image](https://github.com/user-attachments/assets/d796f4d3-2d20-4536-a297-1fc9c6d4f22c)

but, box is not include this ,this is virtualbox runtime
![image](https://github.com/user-attachments/assets/a9c63344-22dd-40bf-b34c-82413ee517b8)

cannot run boxs, you need to change name for find differing aspects

**Comment by ivan-hc** [comment]
I'm aware of this, to save disk space.

Also the developer of Conty knows this https://github.com/Kron4ek/Conty/issues/140#issuecomment-2252190339

Him said that him will work on Conty istances that share the same runtime directory.

**Comment by ivan-hc** [comment]
Hey, this issue has been solved in https://github.com/Kron4ek/Conty/issues/153

Here are Boxes and VirtualBox running together

![Istantanea_2024-08-01_19-45-27](https://github.com/user-attachments/assets/edbd80c6-d955-4109-9bb3-550f8a7a5495)

Download them again.
