### ISSUE TITLE
warning, cannot load local gtk settings.ini

### ISSUE THREAD

**Issue by qq895311511** [ivan-hc/Boxes-appimage#5]
![image](https://github.com/user-attachments/assets/0a471e7c-976d-4bf7-b0ad-9fbc09265e09)
![image](https://github.com/user-attachments/assets/7634b117-93a3-4120-b2fd-afbe5d333c69)

**Comment by ivan-hc** [comment]
@Samueru-sama do you know how should I fix this?

**Comment by Samueru-sama** [comment]
I can't replicate, I get different error instead but the app is using my gtk theme: 

![image](https://github.com/user-attachments/assets/4bfdb826-d444-4e71-b52e-9e4aa121ec8a)

**Comment by qq895311511** [comment]
the bug is fixed.
just need to download themes in my host os.

![image](https://github.com/user-attachments/assets/72b53009-09ec-4ae8-b2c1-bd85f13342ec)
![image](https://github.com/user-attachments/assets/93f50b7e-30b3-4c09-b395-8d3fc2bc231e)
